
- hosts: all
  gather_facts: no
  become: true
  vars:
    companyname: USDA
    location: USA
  tasks:
    - name: Display Variable Value
      debug:
       msg: "My company name is {{companyname}}"
