


---
- hosts: all
  gather_facts: no
  become: true
  vars_files:
    vars.yml  
  tasks:
    - name: Install Apache Server
      apt:
        name: apache2
        state: latest
    - name: Enable the Apache Server
      systemd:
        name: apache2
        enabled: true
    - name: Copy index.html
      template:
        src: /home/ansible/index.html
        dest: /var/www/html/index.html
      notify:
        Start the apache Server
  handlers:
    - name: Start the apache Server
      systemd:
        name: apache2
        state: started
...

