
---
- hosts: all
  gather_facts: no
  become: true
  tasks:
    - name: Install Apache Server
      apt:
        name: apache2
        state: latest
    - name: Enable the Apache Server
      systemd:
        name: apache2
        enabled: false
    - name: Start the apache Server
      systemd:
        name: apache2
        state: started
      tags:
        start
    - name: Copy index.html
      copy:
        src: index.html
        dest: /var/www/html/index.html
      tags:
        copy
...
