
---
- hosts: all
  gather_facts: no
  become: true
  vars:
    companyname: CodeDistrict
    location: Pak
  tasks:
    - name: Install Apache Server
      apt:
        name: apache2
        state: latest
    - name: Copy index.html
      template:
        src: index.html
        dest: /var/www/html/index.html
      tags:
        template
    - name: Start the apache Server
      systemd:
        name: apache2
        state: started
      tags:
        start
...
