
---
# tasks file for docker_install

- name: Install required packages
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    state: present
    update_cache: yes

- name: Add Docker GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu focal stable
    state: present
    filename: docker

- name: Install Docker CE
  apt:
    name: docker-ce
    state: latest
    update_cache: yes

- name: Add user to docker group
  user:
    name: ansible
    groups: docker
    append: yes

- name: Enable and start Docker service
  systemd:
    name: docker
    enabled: yes
    state: started

- name: Run hello-world container
  command: docker run hello-world
  register: hello_output
  changed_when: false

- name: Show hello-world output
  debug:
    var: hello_output.stdout

